// Generated by Scripts/pin-model-digests.py. Do not edit.
//
// Digests for every downloadable speech model, compiled into the binary
// rather than shipped as a resource. See the script for why.

enum ModelDigests {
    static let json = #"""
{
  "_comment": "Generated by Scripts/pin-model-digests.py. A lockfile, not a signature: it records what the model repositories served when it was taken, so any later change is detected. Do not hand-edit.",
  "models": {
    "distil-whisper_distil-large-v3_turbo_600MB": {
      "commit": "0f63a7800b00dd0226abd051b906c246e1907482",
      "files": {
        "AudioEncoder.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "94b7b86bea508311eb4f6f60fa2692bdd4ed566ecd54a80f463f22ece82d8a33",
          "size": 243
        },
        "AudioEncoder.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "ed121e756d637301566cc86a4787e2adece71c438774ed1e5652a76d4f9ed62b",
          "size": 348
        },
        "AudioEncoder.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "b54c6aa1977ac1da0b74d269f877b41cf28d6819",
          "size": 2002
        },
        "AudioEncoder.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "60d60c6ff73e46283e7f0a332a6fed781337a89e",
          "size": 7567995
        },
        "AudioEncoder.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "98410d88d5243d74e5e5210febfbb84dd7a9392793f0fb320b46ab8b92c52a15",
          "size": 353908416
        },
        "MelSpectrogram.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "091a361134891f94e613562771beea0d93a9aefbc6984ba86c60f856e07a508f",
          "size": 243
        },
        "MelSpectrogram.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "f3c5778c86d6fbc6a9817a56dbcac05a946a4d95c77f6db8355572f3be9e9a68",
          "size": 329
        },
        "MelSpectrogram.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "13fcb044275d5f71dbffab0fdbcb3b173bb0955e",
          "size": 1850
        },
        "MelSpectrogram.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "4cbec89bb76fb8a5edf95927d3a888989f287ff4",
          "size": 10187
        },
        "MelSpectrogram.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "7a80bf139bea628069316903af7fb674a8d319233ab98f9d74b1c840915a4ef0",
          "size": 373376
        },
        "TextDecoder.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "013f68d396d51f281bef4db5e0c3b8eb8df147f657830c8df34589875848663d",
          "size": 243
        },
        "TextDecoder.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "db10bd19b00bccc9b7d2a5a8317b6d73be16c01f78b3b3da47040ae604347b11",
          "size": 633
        },
        "TextDecoder.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "fc84d65a5f53b3219ac268318a013027ad09d488",
          "size": 4750
        },
        "TextDecoder.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "5d4d156229f9252f428c3bf38214bbcc8cd497b7",
          "size": 102862
        },
        "TextDecoder.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "4e8e3906c4f1717fe848f6d45e6e052fc3d6048ec24d3a34e23e1c972b10bc84",
          "size": 238986036
        },
        "TextDecoderContextPrefill.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "177b3e51ce243362f79be85ee3d422665b49225bbb1993d72678a79a4788372e",
          "size": 243
        },
        "TextDecoderContextPrefill.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "e1fb28c51275e24a93535cf363012bbff21f6d486a8238d5fcf93d6288e2f781",
          "size": 380
        },
        "TextDecoderContextPrefill.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "f0ecc21adcf7c25b5def2361595fe1739c9ec402",
          "size": 2232
        },
        "TextDecoderContextPrefill.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "b4fbec53da6ec0dc7d896bc0421c242d392f0c07",
          "size": 3761
        },
        "TextDecoderContextPrefill.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "26266f85b3830f13b43e4fec705e3999329b1af171b23f6eff4e89fe9c137ae0",
          "size": 6144192
        },
        "config.json": {
          "algorithm": "git-blob-sha1",
          "digest": "35fb9504486c4c3df76f5f84aad0bdffd3de00f6",
          "size": 1156
        },
        "generation_config.json": {
          "algorithm": "git-blob-sha1",
          "digest": "8d1525665be3225ab0cbd947863a3f75fe5a5b2b",
          "size": 2854
        }
      },
      "repo": "argmaxinc/whisperkit-coreml"
    },
    "nvidia_parakeet-tdt-0.6b-v3": {
      "commit": "7dd20fe6b1797d35f5e3307e8b1732d9a178edfe",
      "files": {
        ".gitattributes": {
          "algorithm": "git-blob-sha1",
          "digest": "a6344aac8c09253b3b630fb776ae94478aa0275b",
          "size": 1519
        },
        "Decoder.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "4238c4e81ecd0dc94bd7dfbb60f7e2cc824107c1ffe0387b8607b72833dba350",
          "size": 243
        },
        "Decoder.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "18647af085d87bd8f3121c8a9b4d4564c1ede038dab63d295b4e745cf2d7fb99",
          "size": 554
        },
        "Decoder.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "781350d40ed83511afc3bc31a804e6a543e69d04",
          "size": 3427
        },
        "Decoder.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "95328ba81ca8dceb16c039e62f1a7d447ede43c2",
          "size": 13110
        },
        "Decoder.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "48adf0f0d47c406c8253d4f7fef967436a39da14f5a65e66d5a4b407be355d41",
          "size": 23604992
        },
        "Encoder.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "42e638870d73f26b332918a3496ce36793fbb413a81cbd3d16ba01328637a105",
          "size": 243
        },
        "Encoder.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "d48034a167a82e88fc3df64f60af963ab3983538271175b8319e7d5720a0fb86",
          "size": 485
        },
        "Encoder.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "aecde9a8c4ff70c5b5d227a079650fcf5033caee",
          "size": 2921
        },
        "Encoder.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "93d1301ccde7c2ca447af6c01ab05bfda5a5dd2c",
          "size": 959769
        },
        "Encoder.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "e2020f323703477a5b21d7c2d282c403e371afb5962e79877e3033e73ba6f421",
          "size": 445187200
        },
        "EncoderInt4.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "c296e0229ab5e32412fda92f8dcf47f0e63f0c34e343c0e2654f6c37649d2d79",
          "size": 243
        },
        "EncoderInt4.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "3e6539cd5d5f1c3bd5a01921cd94af85eab609d49d47e1436a16faac958754d6",
          "size": 512
        },
        "EncoderInt4.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "3f3b994be82e93196572b4d7c2c054aefd48f1ad",
          "size": 2954
        },
        "EncoderInt4.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "bf620dded63605d789a724012251649b1a33f5a6",
          "size": 874445
        },
        "EncoderInt4.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "6fcf5596562948c7482e116bdb3f364279bed970893b86737b67fe89f36367d9",
          "size": 297912320
        },
        "Encoder_v2.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "af98d71151609799efbbffc00112fcba4bd91adf0b01135a982c574e91822f9c",
          "size": 243
        },
        "Encoder_v2.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "70628bd4fd25fb554cc0cebc31356723930c885480132bf3ecd1b5dbe71dd0a2",
          "size": 478
        },
        "Encoder_v2.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "af2fb4d2179bdff0eb165993269a8a40eeae6580",
          "size": 1002653
        },
        "Encoder_v2.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "8d2c79e15a4545e08fe3a21fe741e42b8bf24329db81de8fdfacd92388ea5a66",
          "size": 594211328
        },
        "JointDecision.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "bc69ef031ed427e888b1f3889d13eb373655edd5ac9927de20b5dae281b636b7",
          "size": 243
        },
        "JointDecision.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "f56ded0404498e666ffcd84dda0c393924fc3581345ad03e41429ff560cb97b6",
          "size": 534
        },
        "JointDecision.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "dfdc56eca9b9c64d68bcb71ab14d94851720034d",
          "size": 2936
        },
        "JointDecision.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "b7a794f82b0c0f9f98d08de5374831d1bae5858d",
          "size": 9723
        },
        "JointDecision.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "4e0e63d840032f7f07ddb1d64446051166281e5491bf22da8a945c41f6eedb3e",
          "size": 12642764
        },
        "JointDecisionv2.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "1cb3cc9e583d3a9690e5d87611621b489c79eca8ae49a47b915f268f616e76b2",
          "size": 243
        },
        "JointDecisionv2.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "331a558e8131f72f91c49d632f8f8276a01135b936aad2bd82473956dfafe33d",
          "size": 591
        },
        "JointDecisionv2.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "e694d9510efad76e3bdd94e155054991d34bbb72",
          "size": 3587
        },
        "JointDecisionv2.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "2d9288b9065c3c7cedb1c94b44bb43c33c3cf759",
          "size": 11777
        },
        "JointDecisionv2.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "4e0e63d840032f7f07ddb1d64446051166281e5491bf22da8a945c41f6eedb3e",
          "size": 12642764
        },
        "JointDecisionv3.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "26def4bf73dd56d29dee21c8ef97cb8969e62f6120ed1adc91e46828e2737b6c",
          "size": 243
        },
        "JointDecisionv3.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "f5fc08b741400f0088492c9e839418b1e18522f19cba28d361dd030c5f398342",
          "size": 521
        },
        "JointDecisionv3.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "0461ef9e55ba8e8ba0d2cb33b6e1a031b0d481d7",
          "size": 3453
        },
        "JointDecisionv3.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "0a80fde4b1ec61093a03fc0fc3431172db34a4d2",
          "size": 11775
        },
        "JointDecisionv3.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "4e0e63d840032f7f07ddb1d64446051166281e5491bf22da8a945c41f6eedb3e",
          "size": 12642764
        },
        "JointDecisionv3.mlpackage/Data/com.apple.CoreML/model.mlmodel": {
          "algorithm": "sha256",
          "digest": "c31044bcbcc2959ced2a59e8a0177b617aa359fa1ad613b57de5b63a430f9e31",
          "size": 10608
        },
        "JointDecisionv3.mlpackage/Data/com.apple.CoreML/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "4e0e63d840032f7f07ddb1d64446051166281e5491bf22da8a945c41f6eedb3e",
          "size": 12642764
        },
        "JointDecisionv3.mlpackage/Manifest.json": {
          "algorithm": "git-blob-sha1",
          "digest": "e157318e3cbcefd3a0b006c907e158f744c2e925",
          "size": 617
        },
        "MelEncoder.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "811601924d9f2206d3c712cd37668ee728c865c9aadbbbc63742e424e02664a7",
          "size": 243
        },
        "MelEncoder.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "10da3c056f8381d7447527718dc36e137439fffa4ce154f12b3656e8856bf96a",
          "size": 493
        },
        "MelEncoder.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "a8bc453c9f64bb4e5cb2574b0179edcadfaf3740",
          "size": 3178
        },
        "MelEncoder.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "57d0b73aad7b34221dc604addc874178d0a74732",
          "size": 1044136
        },
        "MelEncoder.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "351c7a3bee2bf563472a5b09a2dde37b940d59aa23ef39a201c9885c7f010c61",
          "size": 595166912
        },
        "Melspectrogram_15s.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "69c14cb1c88f889264d81aaf34d927afd46a1fab42b762e2ca506e496f2b0f6b",
          "size": 243
        },
        "Melspectrogram_15s.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "7bf5c6d29eefd6aca3a2775848fc13d169db0d2a399fc42f0d41505403de0c98",
          "size": 400
        },
        "Melspectrogram_15s.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "74e0db48f857946707fcdc0cf52fc8cbd35c0ea1",
          "size": 2804
        },
        "Melspectrogram_15s.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "cf77dba2630004bd8b72177f16f5bf4576a2a9bf",
          "size": 26279
        },
        "Melspectrogram_15s.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "023c2303b7c3a1fafed92fc6ec46c1d43a48c0bbcdf33d6441d383a61747734c",
          "size": 592384
        },
        "ParakeetDecoder.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "c88c077549fa8f428d30a75e3abeb031f3069fb4970e2ba34f451880c6526848",
          "size": 243
        },
        "ParakeetDecoder.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "7b3f7039bd77de949917b8d1fe53d892a925e0cae1ad1b3cca2c5d57b922392c",
          "size": 438
        },
        "ParakeetDecoder.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "5f245d64d6934633eacac16255d2d679b6d3c9df",
          "size": 13739
        },
        "ParakeetDecoder.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "cae05619deee8995ff4532cb34a5ab63fbc14accf38f26479735933170159c9c",
          "size": 36722432
        },
        "ParakeetEncoder_15s.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "d9bc0e8a2ff995d47f651409dfe813571e2772292f22900a0c1c89cb62225ec3",
          "size": 243
        },
        "ParakeetEncoder_15s.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "97d19e4d07164239ad1e566d4a6067c05d794996d6152f18b2dd75ac86bfc221",
          "size": 387
        },
        "ParakeetEncoder_15s.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "e38ef548cc7045ab43bc5afba2b267444a5a83f1",
          "size": 2765
        },
        "ParakeetEncoder_15s.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "667a90e50faeafdff960ae5c330fe39459365cc1",
          "size": 957827
        },
        "ParakeetEncoder_15s.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "fcf39b6d2ff41c623e5ec8c21fdca06100fc390adbbc926fa767d9fbaf35866d",
          "size": 445187200
        },
        "Preprocessor.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "c9beeb989c8d66f8be11df59bc6df277ec76cee404f6865b46243835ef562f6d",
          "size": 243
        },
        "Preprocessor.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "dbde3f2300842c1fd51ef3ff948a0bcffe65ffd2dca10707f2509f32c1d65b1d",
          "size": 486
        },
        "Preprocessor.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "06162c58cf2f5343a0e60f36f843bcdf3cc58527",
          "size": 2841
        },
        "Preprocessor.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "f987e2479228436c49189aa47edb376db74dcff5",
          "size": 28181
        },
        "Preprocessor.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "129b76e3aeafa8afa3ea76d995b964b145fe83700d579f6ff42c4c38fa0968ea",
          "size": 491072
        },
        "README.md": {
          "algorithm": "git-blob-sha1",
          "digest": "b58d9906904932522ce131ce30f5fa9701230384",
          "size": 4285
        },
        "RNNTJoint.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "6123e6464c990b52c62d86bd580a11c746cfcb5a01ae51b9ecbe92cfcef68852",
          "size": 243
        },
        "RNNTJoint.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "8f1dc6e96c2f63c8636f5a09968abd2bff0ded029e5a205886c10228421a029b",
          "size": 394
        },
        "RNNTJoint.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "7b7991530191ff6f46e8ad2095ce3ad910c91806",
          "size": 2703
        },
        "RNNTJoint.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "fac5c21a17e20eed7bef5ce8331fdc1f8f18d443",
          "size": 5508
        },
        "RNNTJoint.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "4e0e63d840032f7f07ddb1d64446051166281e5491bf22da8a945c41f6eedb3e",
          "size": 12642764
        },
        "config.json": {
          "algorithm": "git-blob-sha1",
          "digest": "b6a1d442c414a219be5332e5b9a011631aff1515",
          "size": 475
        },
        "mlpackages/.DS_Store": {
          "algorithm": "git-blob-sha1",
          "digest": "05ef7ba3ed4bde11f2733136eff56a5732aa9429",
          "size": 6148
        },
        "mlpackages/Decoder.mlpackage/Data/com.apple.CoreML/model.mlmodel": {
          "algorithm": "sha256",
          "digest": "8bfdcef9fb1b46a1ec2f3c1895c74ed90644a69105efda370e412a522bd5b353",
          "size": 11672
        },
        "mlpackages/Decoder.mlpackage/Data/com.apple.CoreML/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "48adf0f0d47c406c8253d4f7fef967436a39da14f5a65e66d5a4b407be355d41",
          "size": 23604992
        },
        "mlpackages/Decoder.mlpackage/Manifest.json": {
          "algorithm": "git-blob-sha1",
          "digest": "84f2c2d96570f0c25fb530d3bb01a0fc6485bda9",
          "size": 617
        },
        "mlpackages/Encoder.mlpackage/Data/com.apple.CoreML/model.mlmodel": {
          "algorithm": "sha256",
          "digest": "cfec08b0fb04d25f7f61203e02571091e53d22fc85c47c5cc9699019d2ab0d2a",
          "size": 661900
        },
        "mlpackages/Encoder.mlpackage/Data/com.apple.CoreML/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "e2020f323703477a5b21d7c2d282c403e371afb5962e79877e3033e73ba6f421",
          "size": 445187200
        },
        "mlpackages/Encoder.mlpackage/Manifest.json": {
          "algorithm": "git-blob-sha1",
          "digest": "ef5e89240358aa241b5a6f5fc55777fe75844fff",
          "size": 617
        },
        "mlpackages/JointDecision.mlpackage/Data/com.apple.CoreML/model.mlmodel": {
          "algorithm": "sha256",
          "digest": "130d2712b827b8356667c02494efd117ac8aec2d1c563f169e9d4d350c346301",
          "size": 8820
        },
        "mlpackages/JointDecision.mlpackage/Data/com.apple.CoreML/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "4e0e63d840032f7f07ddb1d64446051166281e5491bf22da8a945c41f6eedb3e",
          "size": 12642764
        },
        "mlpackages/JointDecision.mlpackage/Manifest.json": {
          "algorithm": "git-blob-sha1",
          "digest": "bf201a64eafabb358e9a757d551fedbd5e52af6e",
          "size": 617
        },
        "mlpackages/MelEncoder.mlpackage/Data/com.apple.CoreML/model.mlmodel": {
          "algorithm": "sha256",
          "digest": "0e7ee9681979808688ac650b08349059f0526ebc3bb5ba73cc76e2b414046d72",
          "size": 716613
        },
        "mlpackages/MelEncoder.mlpackage/Data/com.apple.CoreML/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "351c7a3bee2bf563472a5b09a2dde37b940d59aa23ef39a201c9885c7f010c61",
          "size": 595166912
        },
        "mlpackages/MelEncoder.mlpackage/Manifest.json": {
          "algorithm": "git-blob-sha1",
          "digest": "1ba29461ce4ee665b9d2578f32f281fcb2276627",
          "size": 617
        },
        "mlpackages/Preprocessor.mlpackage/Data/com.apple.CoreML/model.mlmodel": {
          "algorithm": "sha256",
          "digest": "abc41e3d6c4f2d401ca445c85aa4884244eabed9bdec7b4ec7e60d691140cdfb",
          "size": 20454
        },
        "mlpackages/Preprocessor.mlpackage/Data/com.apple.CoreML/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "129b76e3aeafa8afa3ea76d995b964b145fe83700d579f6ff42c4c38fa0968ea",
          "size": 491072
        },
        "mlpackages/Preprocessor.mlpackage/Manifest.json": {
          "algorithm": "git-blob-sha1",
          "digest": "c72c40e30e2a3d269c78153aecd4f1a064bf237a",
          "size": 617
        },
        "mlpackages/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "baf586344bfacae3a36ffcc653e60178214a5fdb",
          "size": 9358
        },
        "parakeet_v3_vocab.json": {
          "algorithm": "git-blob-sha1",
          "digest": "c684822ec3b671ebc449c433a7012398d39b8bb0",
          "size": 151122
        },
        "parakeet_vocab.json": {
          "algorithm": "git-blob-sha1",
          "digest": "c684822ec3b671ebc449c433a7012398d39b8bb0",
          "size": 151122
        }
      },
      "repo": "FluidInference/parakeet-tdt-0.6b-v3-coreml"
    },
    "openai_whisper-base.en": {
      "commit": "0f63a7800b00dd0226abd051b906c246e1907482",
      "files": {
        "AudioEncoder.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "c4e096b2abd561f00b9b698401df3fbe1a0d0c8d2476ff19cb4e1995680e827e",
          "size": 243
        },
        "AudioEncoder.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "e316980638e2099e83cb1a93b903717dc12b3c2168d0ab69113764c3767696ba",
          "size": 347
        },
        "AudioEncoder.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "1b82ac5a57544279ce9f5c82c78f6fa5891520cc",
          "size": 1863
        },
        "AudioEncoder.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "31b155b9b8384df140e6f7080248842f9aea1c90",
          "size": 579125
        },
        "AudioEncoder.mlmodelc/model.mlmodel": {
          "algorithm": "sha256",
          "digest": "1d42038f84b508da5ce9b953302387ffedc097c346d36a56b765109002b6080e",
          "size": 79853
        },
        "AudioEncoder.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "74f15e6d2f7694af54e90227cbf22fd6c04082638f163b78a909967b16edc1c7",
          "size": 41189632
        },
        "MelSpectrogram.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "7f77e6457285248f99cd7aa3fd4cc2efbb17733e63e7023ac53abe1f95785d07",
          "size": 243
        },
        "MelSpectrogram.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "dabdc5aa69f6ef4d97dc9499f5c30514e00e96b53b750b33a5a6471363c71662",
          "size": 328
        },
        "MelSpectrogram.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "022c382ec7041de63c59dd98893c3134d01b23aa",
          "size": 1848
        },
        "MelSpectrogram.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "a63d7fa99d6d86db1b76a1f53640cb4aa25e0210",
          "size": 10176
        },
        "MelSpectrogram.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "ee77f9b67765f7abc33f16374081b2389cf1d3a89536187b241950c5a2e5d6c1",
          "size": 354080
        },
        "TextDecoder.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "e870aac5de88676c1ad93cb3939f257e6de30e5235c3f9d7686398ebecafdb8d",
          "size": 243
        },
        "TextDecoder.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "4b23ff9d9fe376f2b86f9cf55af3218560a4e4d692041360510fbad490c0db43",
          "size": 633
        },
        "TextDecoder.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "3da2721e50228dc78a6b79cd010041f5f9c6855d",
          "size": 4753
        },
        "TextDecoder.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "ea1a8b7ddbb9a4104ef627712ef0ceb6fa1d8da2",
          "size": 200444
        },
        "TextDecoder.mlmodelc/model.mlmodel": {
          "algorithm": "sha256",
          "digest": "72f1214f7c8b26e467dd8233572eaa5cbe200f30a36b918d4c289f9fc8c4f401",
          "size": 160348
        },
        "TextDecoder.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "4649599bd2d97f87ffc716e6da2f61a06c06ac5a9424dd23edc3d4bf66fb6221",
          "size": 104121136
        },
        "config.json": {
          "algorithm": "git-blob-sha1",
          "digest": "7af931c5fd7052d3211621654d93a2a3e33dd307",
          "size": 1454
        },
        "generation_config.json": {
          "algorithm": "git-blob-sha1",
          "digest": "cc2edd4b48ab2b8389169e32f930abd8dd8b209d",
          "size": 982
        }
      },
      "repo": "argmaxinc/whisperkit-coreml"
    },
    "openai_whisper-large-v3-v20240930_turbo_632MB": {
      "commit": "0f63a7800b00dd0226abd051b906c246e1907482",
      "files": {
        "AudioEncoder.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "0dd9f529c744ed3c6be67f699588f7aadc4f366b5b7301dc31bd3f199944fbcc",
          "size": 243
        },
        "AudioEncoder.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "ffa9eb76e8e9d9be75a4d527e5249e61d67fd43081c5aa110fd24efa6c8c5ea3",
          "size": 348
        },
        "AudioEncoder.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "5820827b232e51b0e914d1b0e78da9093bda4edb",
          "size": 1974
        },
        "AudioEncoder.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "2c5e6fcd0383e7762f89abd23e34b3fe4cc356ab",
          "size": 7589739
        },
        "AudioEncoder.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "e4740fa28ed65907af754af893dfce98473fafb84dd8d718ad346985fe7678c1",
          "size": 421968768
        },
        "MelSpectrogram.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "c5be419f8622083ac7046306400643539f0e7577c843448c36defc090d41e7ce",
          "size": 243
        },
        "MelSpectrogram.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "98efa1e351b759e078c4044668926d32bee886caf7596ae897e08e21da45565a",
          "size": 329
        },
        "MelSpectrogram.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "fa0c2e5993006c311ba50d307cf563ae10a16b5f",
          "size": 1850
        },
        "MelSpectrogram.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "16b67b0978ac178a7540e8520915d2473d4bae03",
          "size": 10143
        },
        "MelSpectrogram.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "009d9fb8f6b589accfa08cebf1c712ef07c3405229ce3cfb3a57ee033c9d8a49",
          "size": 373376
        },
        "TextDecoder.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "4b5119bdc621c3c494f63846dc3ed43852e88826fc3b6345d42272d4b7e67724",
          "size": 243
        },
        "TextDecoder.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "605dad4099a82cf2c7afe93e6d8e322f1c16d4160ab27bd017ec2517b81c1bdd",
          "size": 633
        },
        "TextDecoder.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "d85561cc6242beaa37dbe3fbd510e7384a3f5c84",
          "size": 4924
        },
        "TextDecoder.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "8958c6803ae0c8eea0ea4ce9de9d632d407e5db3",
          "size": 217177
        },
        "TextDecoder.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "d69700903d518ada33170ab77faaaf464496fb9ff65752c6d5a6109aa2fb02db",
          "size": 203199860
        },
        "TextDecoderContextPrefill.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "97639d36c7b137ea51c3c39b175911788f4d4a601ab03cd67a4b14164c3145e1",
          "size": 243
        },
        "TextDecoderContextPrefill.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "2c159f5c862ec187092ea58e755d8c0b298952e22f3d75da023d7693c1c7389e",
          "size": 380
        },
        "TextDecoderContextPrefill.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "0b95fc53b8ba1b1a2c456910e6a9d9b1df36d6ea",
          "size": 2240
        },
        "TextDecoderContextPrefill.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "3e58aef47f462dfe6e83a60084bf2f2b7f4e93e2",
          "size": 4092
        },
        "TextDecoderContextPrefill.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "1310070082639173e9d81508c5f220692d489e85655aa6883cc1c7506da7fcfd",
          "size": 12288192
        },
        "config.json": {
          "algorithm": "git-blob-sha1",
          "digest": "f6c3db01a3124f90b3bfbf3d58e47ba5de1f5ccd",
          "size": 1149
        },
        "generation_config.json": {
          "algorithm": "git-blob-sha1",
          "digest": "a023f6f947b0fc4ab7a2986a1c23b014836ec720",
          "size": 2767
        }
      },
      "repo": "argmaxinc/whisperkit-coreml"
    },
    "openai_whisper-small.en": {
      "commit": "0f63a7800b00dd0226abd051b906c246e1907482",
      "files": {
        "AudioEncoder.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "211457b92a0ced67bb8625efe39799a0030c4fc71eb87d7284ea81043caccde7",
          "size": 243
        },
        "AudioEncoder.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "d8be820f6e3406891bdd25effc0e3b4cac712064c8bcf74053d8abec7e97c585",
          "size": 347
        },
        "AudioEncoder.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "9f06d3ae86653eca79c3b7b8fbde3379d72185ee",
          "size": 1868
        },
        "AudioEncoder.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "0dd59f0859f9a655599067124f0583a5263a0be5",
          "size": 1636668
        },
        "AudioEncoder.mlmodelc/model.mlmodel": {
          "algorithm": "sha256",
          "digest": "68ca04660b8b050c68ca54c27d97c47e4133bc591422cb7009de8922d56fb8c9",
          "size": 155271
        },
        "AudioEncoder.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "f92860042703b3679071e7eeb03c861e52bf0e1da38943cf7c37eb5fecfb3abe",
          "size": 176323456
        },
        "MelSpectrogram.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "7f77e6457285248f99cd7aa3fd4cc2efbb17733e63e7023ac53abe1f95785d07",
          "size": 243
        },
        "MelSpectrogram.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "dabdc5aa69f6ef4d97dc9499f5c30514e00e96b53b750b33a5a6471363c71662",
          "size": 328
        },
        "MelSpectrogram.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "022c382ec7041de63c59dd98893c3134d01b23aa",
          "size": 1848
        },
        "MelSpectrogram.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "a63d7fa99d6d86db1b76a1f53640cb4aa25e0210",
          "size": 10176
        },
        "MelSpectrogram.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "50b463279c2f0089cd82a82f6c091675c6d499515562067c47c706f59051e4a0",
          "size": 354080
        },
        "TextDecoder.mlmodelc/analytics/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "63c717108d44630649d42e255ac94739c725937bf8e16ae6787e04c3a4f0ec6a",
          "size": 243
        },
        "TextDecoder.mlmodelc/coremldata.bin": {
          "algorithm": "sha256",
          "digest": "f596a022005761b7f18e448b6c34be2b6f6a2797d11371145e4544eb25fa411d",
          "size": 633
        },
        "TextDecoder.mlmodelc/metadata.json": {
          "algorithm": "git-blob-sha1",
          "digest": "5e007d172fe95cc09cda8ec733ba05285924628b",
          "size": 4757
        },
        "TextDecoder.mlmodelc/model.mil": {
          "algorithm": "git-blob-sha1",
          "digest": "8dcba81a96f6b056bd6f509fab423fbc62991592",
          "size": 406425
        },
        "TextDecoder.mlmodelc/model.mlmodel": {
          "algorithm": "sha256",
          "digest": "702d2df1b6a37b49a4e21f8024c230148e3b0f7c6c4e9001deb5501b496971f2",
          "size": 326032
        },
        "TextDecoder.mlmodelc/weights/weight.bin": {
          "algorithm": "sha256",
          "digest": "a71a58c723a8c379fbc0ba666d6a3d3dd85d84d34ee8665697d2edab52f2f6b1",
          "size": 307285808
        },
        "config.json": {
          "algorithm": "git-blob-sha1",
          "digest": "4b37ac79e4370895417e0c9a1b125c39f3943a09",
          "size": 1460
        },
        "generation_config.json": {
          "algorithm": "git-blob-sha1",
          "digest": "0470982bb604cea5a3c6d011d9876e5899859b0b",
          "size": 1076
        }
      },
      "repo": "argmaxinc/whisperkit-coreml"
    }
  }
}

"""#
}
