#!/usr/bin/env python3
"""Regenerates Sources/PlainsayCore/Resources/model-digests.json.

Speech models are downloaded at first run and executed. Neither WhisperKit nor
FluidAudio verifies what it just fetched: WhisperKit hashes a file only to
decide whether an *already cached* copy can be reused (and enforces a hash
strictly only in offline mode), and FluidAudio uses ETags purely to resume
interrupted transfers. So the one place unsigned code enters an otherwise
signed-and-notarised chain had no check at all — raised in the external review
(#1, finding 6) and tracked as #27.

This records the digests Hugging Face publishes for each model, so the app can
recompute them locally after downloading and refuse to load anything that does
not match. It deliberately does NOT download the models: the digests come from
the repository tree API, which is a few hundred kilobytes of JSON instead of
several gigabytes of weights.

What the pin is, and what it is not
-----------------------------------
This is a lockfile, not a signature. The digests are whatever the repository
served at the moment they were taken, exactly as `Package.resolved` records
whatever a dependency resolved to. It cannot tell you the upstream model was
honest on that day. What it does do is make any *later* change detectable — the
realistic attack being an upstream repo, or an account with push access to it,
starting to serve something different than it did when this was reviewed. That
is worth having, and overstating it would be worse than not having it.

Usage:
    python3 Scripts/pin-model-digests.py            # rewrite the manifest
    python3 Scripts/pin-model-digests.py --check    # fail if it is out of date
"""

import json
import pathlib
import sys
import urllib.error
import urllib.request

API = "https://huggingface.co/api/models"

# Every model the app can download. Keys are `OnDeviceModel.rawValue`, except
# the Parakeet entry, whose files come from FluidAudio's own repo.
MODELS = {
    "openai_whisper-base.en": ("argmaxinc/whisperkit-coreml", "openai_whisper-base.en"),
    "openai_whisper-small.en": ("argmaxinc/whisperkit-coreml", "openai_whisper-small.en"),
    "distil-whisper_distil-large-v3_turbo_600MB": (
        "argmaxinc/whisperkit-coreml",
        "distil-whisper_distil-large-v3_turbo_600MB",
    ),
    "openai_whisper-large-v3-v20240930_turbo_632MB": (
        "argmaxinc/whisperkit-coreml",
        "openai_whisper-large-v3-v20240930_turbo_632MB",
    ),
    "nvidia_parakeet-tdt-0.6b-v3": ("FluidInference/parakeet-tdt-0.6b-v3-coreml", ""),
}

MANIFEST = pathlib.Path("Sources/PlainsayCore/Resources/model-digests.json")


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "plainsay-pin-model-digests"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.load(response)


def tree(repo, path):
    """Every file under `path`, recursively."""
    suffix = f"/{path}" if path else ""
    return fetch(f"{API}/{repo}/tree/main{suffix}?recursive=true")


def head_commit(repo):
    """The commit the digests were read at, recorded so a human can diff."""
    return fetch(f"{API}/{repo}")["sha"]


def digests_for(repo, path):
    """Maps each file to the strongest digest Hugging Face publishes for it.

    LFS files — the weights, and everything else of any size — carry a real
    sha256 of their contents. Small files are plain git blobs, where the only
    published digest is git's own sha1 over "blob <len>\\0" + contents. Both are
    recomputable locally, so both are recorded, tagged so the app knows which
    function to apply rather than guessing from the digest's length.
    """
    files = {}
    prefix = f"{path}/" if path else ""
    for entry in tree(repo, path):
        if entry.get("type") != "file":
            continue
        relative = entry["path"]
        if prefix and relative.startswith(prefix):
            relative = relative[len(prefix):]
        lfs = entry.get("lfs")
        if lfs and lfs.get("oid"):
            files[relative] = {"algorithm": "sha256", "digest": lfs["oid"], "size": lfs.get("size", entry.get("size"))}
        else:
            files[relative] = {"algorithm": "git-blob-sha1", "digest": entry["oid"], "size": entry.get("size")}
    if not files:
        raise SystemExit(f"no files found for {repo} {path!r} — refusing to write an empty pin")
    return files


def build():
    manifest = {
        "_comment": (
            "Generated by Scripts/pin-model-digests.py. A lockfile, not a signature: "
            "it records what the model repositories served when it was taken, so any "
            "later change is detected. Do not hand-edit."
        ),
        "models": {},
    }
    for name, (repo, path) in MODELS.items():
        sys.stderr.write(f"pinning {name} from {repo}...\n")
        manifest["models"][name] = {
            "repo": repo,
            "commit": head_commit(repo),
            "files": digests_for(repo, path),
        }
    return manifest


def main():
    check = "--check" in sys.argv
    built = build()
    rendered = json.dumps(built, indent=2, sort_keys=True) + "\n"

    if check:
        current = MANIFEST.read_text() if MANIFEST.exists() else ""
        if current != rendered:
            sys.stderr.write(
                "model-digests.json is out of date with the upstream repositories.\n"
                "This is expected when a model is republished; review what changed "
                "before regenerating, because the whole point of the pin is that a "
                "change is visible.\n"
            )
            return 1
        sys.stderr.write("model-digests.json matches upstream\n")
        return 0

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(rendered)
    total = sum(len(m["files"]) for m in built["models"].values())
    sys.stderr.write(f"wrote {MANIFEST} — {len(built['models'])} models, {total} files\n")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except urllib.error.URLError as error:
        sys.stderr.write(f"could not reach Hugging Face: {error}\n")
        sys.exit(2)
